# Reemplaza esto con el ID exacto del proyecto que sale en la página de la UCT
sonar.projectKey=AQUI_EL_ID_DEL_PROYECTO
sonar.projectName=FastBite

# Dónde está tu código
sonar.sources=.

# Dónde está el reporte de pruebas que hicimos
sonar.python.coverage.reportPaths=coverage.xml

# La URL del servidor de tu universidad
sonar.host.url=https://sonarqube.inf.uct.cl

# Lo que NO queremos que analice (para que no baje la nota)
sonar.exclusions=**/migrations/**, **/venv/**, manage.py, core/settings.py, **/tests.py