# Generated by Django 6.0.5 on 2026-05-07 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("categoria", models.CharField(max_length=50)),
                ("horario", models.CharField(max_length=100)),
                ("tiempo_entrega", models.CharField(max_length=50)),
                ("imagen_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("categoria", models.CharField(max_length=50)),
                ("disponible", models.BooleanField(default=True)),
                ("imagen_url", models.URLField(blank=True)),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="catalogo.restaurante",
                    ),
                ),
            ],
        ),
    ]
