# Generated by Django 6.0.5 on 2026-06-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_pin_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('porcentaje', models.PositiveIntegerField(help_text='Descuento en porcentaje (ej: 20 para 20%)')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pin_entrega',
            field=models.CharField(blank=True, default='', help_text='PIN de 4 dígitos para verificar la entrega presencial.', max_length=4),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.cupondescuento'),
        ),
    ]
