# Generated by Django 6.0.5 on 2026-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_cupondescuento_pedido_descuento_aplicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('en_camino', 'En Camino'), ('listo_despacho', 'Listo para despacho'), ('listo_retiro', 'Listo para retirar'), ('retirado', 'Retirado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
