# Generated by Django 5.2.15 on 2026-06-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
