# Generated by Django 6.0.5 on 2026-06-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0012_alter_pedido_direccion_entrega"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="direccion_entrega",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
