# Generated by Django 6.0.5 on 2026-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('repartidor', 'Repartidor'), ('restaurante', 'Restaurante')], max_length=20),
        ),
    ]
