# Generated by Django 6.0.5 on 2026-06-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_alter_perfilusuario_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
