# Generated by Django 5.2.15 on 2026-06-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfilusuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
